# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
